version: '2'
services:
  web:
    build: .
    restart: always
    volumes:
      - /etc/ssl/private/coala.io:/etc/ssl/private/coala.io:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - outside
networks:
  outside:
    external: true
