version: '2'
services:
  web:
    build: .
    restart: always
    expose:
      - 8000
    env_file: .secrets
  lb:
    image: dockercloud/haproxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
      - web
    networks:
      - outside
      - default
networks:
  outside:
    external: true
