version: '2'
services:
  cobot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file: .secrets
    environment:
      - BOT_NAME=cobot
      - REDIS_URL=redis://redis:6379/cobot
    links:
      - redis
  redis:
    image: redis:alpine
